### ISSUE TITLE
Kontakt zum Author Jacob Zhang

### ISSUE THREAD

**Issue by Oldchamp** [jacbz/anki_french#16]
Ich möchte dem Author von anki_french gerne eine Vorschlag unterbreiten und ihm dazu Daten in Form einer umfangreichen, von mir erstellten  Exceltabelle (basierend auf Oxford 5000) zur Verfügung stellen. 
Es ist mir aber trotz langwieriger Bemühungen nicht gelungen, den Author mittels E-Mail zu kontaktieren.
Es wäre schön, wenn er auf diese Mail antorten würde.

**Comment by jacbz** [comment]
Ich habe keine Mail erhalten. Gerne die Daten einfach hier hochladen, es ist immerhin ein kollaboratives Projekt.

**Comment by Oldchamp** [comment]
> Ich habe keine Mail erhalten. Gerne die Daten einfach hier hochladen, es ist immerhin ein kollaboratives Projekt.

Danke für die Antwort. Aber wie lade ich die Exceltabelle "einfach hier hoch". Für mein Verständnis bräuchte ich ihre E-Mail-Adresse, dammit ich die Exceltabelle als Anhang hochladen kann und auch, um Ihnen meine Idee darzulegen. Ich bin mit der Handhabung von Github nicht vertaut, 
[HW-5_Vok+BSatz_(A1-C1) (Level+Unit) EK .xlsx](https://github.com/user-attachments/files/16482295/HW-5_Vok%2BBSatz_.A1-C1.Level%2BUnit.EK.xlsx)
[HW-5_Vok+BSatz_(A1-C1) (Unit+Alpha) EK .xlsx](https://github.com/user-attachments/files/16482296/HW-5_Vok%2BBSatz_.A1-C1.Unit%2BAlpha.EK.xlsx)

**Comment by Oldchamp** [comment]
Hallo Herr Zhang,

ich habe die Daten hochgeladen und mangels anderer Möglichkeiten in der einen Exceldatei meine Idee unterbreitet. 

Es wäre für mich recht hilfreich, wenn Sie mir eine E-Mail an meine Adresse schicken würde, damit ich weiß, wie Sie zu dem 

unterbreiteten Vorschlag stehen. 

Wenn Sie die Idee eines Englisch-Decks aufgreifen würden, würde das sicher allen Englischlernenden weltweit große Freude bereiten. 

Da es aber andererseits mit sehr viel Arbeit verbunden wäre, könnte ich auch eine Ablehnung dieser Idee voll und ganz verstehen.

 

Mit freundlichen Grüßen

Erich Körber

 

 

Von: Jacob Zhang ***@***.***> 
Gesendet: Samstag, 3. August 2024 13:05
An: jacbz/anki_french ***@***.***>
Cc: Oldchamp ***@***.***>; Author ***@***.***>
Betreff: Re: [jacbz/anki_french] Kontakt zum Author Jacob Zhang (Issue #16)

 

Ich habe keine Mail erhalten. Gerne die Daten einfach hier hochladen, es ist immerhin ein kollaboratives Projekt.

**Comment by jacbz** [comment]
Die Grundidee dieses Decks, und was es von anderen Vokabellisten abhebt (die man vor allem in Schulbüchern etc. findet), ist, dass es auf statistischer Häufigkeit basiert. Meiner Meinung nach werden in den meisten Lernbüchern zu viele "unnütze" Vokabeln beigebracht, die nur in isolierten Kontexten verwendet werden. Auch in der gegebenen Excelliste finden sich viele Vokabeln, die in einem A1-Kontext komplett unnötig sind (z.B. "ordinal number", "spice market"). Nach der mathematisch bewiesenen Häufigkeit zu lernen ist ein wesentlich effizienterer Ansatz.

Dieses Deck basiert auf der Häufigkeitsliste aus dem Buch "A Frequency Dictionary of French" (2009, Routledge). Ein potentielles Englisch-Deck würde daher ebenfalls auf einer Häufigkeitsliste basieren, z.B. "A Frequency Dictionary of Contemporary American English" (2010, Routledge), oder "A Frequency Dictionary of British English" (2023, Routledge). Allerdings ist ein Englisch-Deck momentan nicht geplant. Ich arbeite grade an einem Japanisch-Deck, das auf "A Frequency Dictionary of Japanese" (2013, Routledge) basiert.

**Comment by Oldchamp** [comment]
Hallo Herr Zhang,

vielen Dank für ihre Antwort. 

Ich stimme Ihnen persönlich völlig zu, dass in den offiziellen Stufen, in die der zu erwerbende Wortschatz eingeteilt ist, viele unnötige Vokabeln enthalten sind, und ich persönlich habe mich bei meiner eigenen Beschäftigung mit Englisch an einer mir zur Verfügung stehenden Häufigkeitsliste (sie umfasst die ersten 3000 Vokabeln) orientiert, weil auch mir das Lernen nach Häufigkeit am logischsten erscheint.

 

Leider ist dieses effiziente, auf Häufigkeit basierende Herangehen, wie Sie richtig angemerkt haben, beim Vokabellernen im Englischunterricht an deutschen Gymnasien nicht üblich. 

Da ich aber vor allem meine beiden Enkel unterstützen wollte, habe ich die Ihnen zugeschickten Exceldateien, basierend auf den offiziellen Leveln, wie sie in den Lehrplänen angegeben werden, erstellt. Das Lernen aus diesen Exceldateien ist aber recht mühsam, daher mein Wunsch, bei Anki etwas Besseres zu finden. Kriterien sind für mich dabei Beispielsätze mit Übersetzung und guter Vertonung der Vokabeln und Sätze (in manchen Decks ist diese Vertonung ein Graus).

 

Ich wünsche Ihnen bei Ihrer Arbeit an dem Japanischen Deck viel Freude und werde Ausschau halten, ob Sie vielleicht doch noch in der Zukunft ein Englisches Deck veröffentlichen.

Bis dahin werde ich prüfen, welches der verfügbaren Englischen Decks meine Enkel beim Englischlernen unterstützen kann.

 

Mit freundlichen Grüßen

Erich Körber

 

Von: Jacob Zhang ***@***.***> 
Gesendet: Sonntag, 4. August 2024 15:16
An: jacbz/anki_french ***@***.***>
Cc: Oldchamp ***@***.***>; State change ***@***.***>
Betreff: Re: [jacbz/anki_french] Kontakt zum Author Jacob Zhang (Issue #16)

 

Die Grundidee dieses Decks, und was es von anderen Vokabellisten abhebt (die man vor allem in Schulbüchern etc. findet), ist, dass es auf statistischer Häufigkeit basiert. Meiner Meinung nach werden in den meisten Lernbüchern zu viele "unnütze" Vokabeln beigebracht, die nur in isolierten Kontexten verwendet werden. Auch in der gegebenen Excelliste finden sich viele Vokabeln, die in einem A1-Kontext komplett unnötig sind (z.B. "ordinal number", "spice market"). Nach der mathematisch bewiesenen Häufigkeit zu lernen ist ein wesentlich effizienterer Ansatz.

Dieses Deck basiert auf der Häufigkeitsliste aus dem Buch "A Frequency Dictionary of French" (2009, Routledge). Ein potentielles Englisch-Deck würde daher ebenfalls auf einer Häufigkeitsliste basieren, z.B. "A Frequency Dictionary of Contemporary American English" (2010, Routledge), oder "A Frequency Dictionary of British English" (2023, Routledge). Allerdings ist ein Englisch-Deck momentan nicht geplant. Ich arbeite grade an einem Japanisch-Deck, das auf "A Frequency Dictionary of Japanese" (2013, Routledge) basiert.
