### ISSUE TITLE
[Hilfe] Hinzufügen eines Feldes um die Antwort einzutippen

### ISSUE THREAD

**Issue by Vartroc** [jacbz/anki_french#20]
Erst einmal danke für dieses wundervolle Deck. Da ich von Phase 6 komme, bin ich es gewohnt, die Antwort einzutippen. Nun wäre meine Frage: Wie kann ich das hinkriegen? Meine schwachen html Kenntnisse sind so weit gekommen (Bearbeitung der Vorlage):
```
<div>
  <input type="text" id="userAnswer" class="user-input" placeholder="Type your answer here..." />
</div>
```
Das Problem damit ist aber, dass die Antwort nicht überprüft wird.

**Comment by jacbz** [comment]
Um die Antwort einzutippen, kannst du jeweils in der Vorderseite und Rückseite ```{{type:Definition}}``` (FR -> DE)  bzw. ```{{type:Wort}}``` (DE -> FR) einfügen.

Ich kann es allerdings nicht empfehlen, weil es das Lernen ziemlich ausbremst. Zudem stehen im Deck eher die Beispielsätze im Fokus; die Definitionen sind nur "Gedächtnisstützen". Ich empfehle daher, lieber den Beispielsatz der Vorderseite im Kopf zu übersetzen.

**Comment by Vartroc** [comment]
Danke für den Tipp, ich werde einfach beide Methoden ausprobieren, und schauen was, für mich, besser funktioniert
