### ISSUE TITLE
Showing same example sentence over again

### ISSUE THREAD

**Issue by daminpark** [jacbz/anki_french#21]
Hi, really loving your deck, thank you so much. One problem I've been having, and I don't think it's always been the case, but recently all the example sentences have been the same and not randomized. Do you know why this might be?

I was also wondering if there was a way to auto-play the sentences in French and unhide the translation of the example sentence. I tried looking at the code but I was pretty confused.

**Comment by jacbz** [comment]
Which device are you using? Does it occur on both desktop and mobile? Randomization of the example sentences is a bit tricky, since front and back sides have to be synced, which is achieved with a neat little script called [anki-persistence](https://github.com/SimonLammer/anki-persistence).

To auto-play sentences, add this line at the end of the `initAudioButtons ` function:

```js
async function initAudioButtons(within = document) {
  ...
 document.querySelector('.play-sentence').click();
}

```
To disable spoilers, adjust the `refreshExampleSentences` function, removing the `spoiler` class:

```js
function refreshExampleSentences() {
  ...
  sentencesInner.innerHTML = frenchFirst
    ? `<div class="fr">${fr}</div><span class="de">${de}</span>`
    : `<div class="de">${de}</div><span class="fr">${fr}</span>`;
  ...
}
```

**Comment by daminpark** [comment]
Ah thanks so much! That fixed everything. I actually customised the Front card of the deck which is why I think it started messing up with regards to the randomisation. I've reverted it back and it's working perfectly. One tiny niggle is that the sentence plays immediately, i.e. not waiting for the audio of the word to finish. Is there an easy fix to that? Or even just a 3 second delay would work I think.

**Comment by jacbz** [comment]
Sure, instead of `document.querySelector('.play-sentence').click();` you can do:

```js
setTimeout(() => {
  document.querySelector('.play-sentence').click();
}, 3000);
```

**Comment by jacbz** [comment]
I've just released an update that adds easily accessible configuration options. Now you can simply set `autoPlaySentence` to `true` and `hideSpoilers` to `false` at the top.

Let me know if you have more customization suggestions!

**Comment by daminpark** [comment]
Thanks, super cool!

I'm finding the German translations aren't very accurate, maybe you could use deepl for more accurate translations? I would do it myself but because all the french and german translations are all in one field I'm not really sure how to do it.

**Comment by daminpark** [comment]
« Tu ne m’as pas regardé quand je suis entré ! » s’est exclamé Jean.

« Tu t’es regardé dans le miroir avant de sortir ? », a demandé sa mère.

These two I saw today, and the German was quite off, quite a bit shortened I felt.

**Comment by jacbz** [comment]
Thanks for the report. I've been working to improve the sentence system. The new version, which may take some months to complete, will feature 100.000+ improved sentences.
