### ISSUE TITLE
Karten mit hohem Rang werden im Fr-De Stapel zu früh aktiviert

### ISSUE THREAD

**Issue by hainkind** [jacbz/anki_french#28]
Hallo,
wenn ich das Deck neu hinzufüge werden einige Karten mit sehr hohem Rang im ersten Batch aktiviert. Z.b. le gras, le col, déceler, le trajet
Das Problem ist aber nur im Fr-De Stapel, im De-Fr sind sie nicht aktiviert. 
Nun bin ich neu bei Anki und weiss nicht ob das Problem nicht vor dem Bildschirm sitzt...

**Comment by jacbz** [comment]
Vielen Dank für die Meldung!

Ich habe den Fehler gefunden und behoben. Wenn du magst kannst du das Deck erneut herunterladen!
