### ISSUE TITLE
Beispielsätze enthalten nicht das zu lernende Wort

### ISSUE THREAD

**Issue by arakis** [jacbz/anki_french#5]
Warum enthalten viele Beispielsätze nicht das betroffene Wort?

https://github.com/jacbz/anki_french/blob/main/cards/0027_mettre.yml

Hier wird z.B. das Wort mettre in den meisten Beispielsätzen nicht verwendet.

**Comment by jacbz** [comment]
Es wird doch überall mettre verwendet, im passé composé (avoir mis).

**Comment by arakis** [comment]
Oh, da schlägt die Grammatik zu 🙈 Danke für die Erklärung 🙃
