### ISSUE TITLE
Update der Grammatikbibliothek funktioniert nicht mehr

### ISSUE THREAD

**Issue by remggo** [jacbz/anki_french#6]
Seit becc8be werden die Änderungen an den Card Templates nicht mehr richtig importiert. Ich habe auch schon probiert eine komplett frische Anki Datenbank zu nutzen für den Import.

Ich verwende die Optionen 
- "Update notes" - always
- "update notetypes" - always

In der Vergangenheit hat das immer gut geklappt, z.b. beim Einführen der Konjungationstabelle oder der Grammatikbibliothek.

Für Ideen wäre ich sehr dankbar.

**Comment by jacbz** [comment]
Hi, was meinst du mit Änderungen an den Card Templates? Wie sieht der Code in den Vorlagen bei dir aus?

**Comment by remggo** [comment]
Ich meine die Änderungen an der Grammatikbibliothek (mit den zugefügten Thematischen Wortlisten)

Hier weiter unten sollten die Wortlisten ja erscheinen:
![grafik](https://github.com/user-attachments/assets/601d869a-abcd-406d-9f41-0a7be30d6d50)


Card Template Back: https://gist.github.com/remggo/9bb4647749dc753027d8631c8b1d9ffd

Ich denke, dass [hier in Zeile 596](https://gist.github.com/remggo/9bb4647749dc753027d8631c8b1d9ffd#file-card_back-html-L596) zu wenig `categories` aus `grammar` rauskommen. Wenn ich den Code richtig ansehe, müsste `_FR5000_grammar.json`  nicht richtig aktualisiert werden bei einem Update des Decks. [Hier wird das grammar dict geladen](https://gist.github.com/remggo/9bb4647749dc753027d8631c8b1d9ffd#file-card_back-html-L387)

**Comment by remggo** [comment]
Ich habe aus meinem `collection.media` Ordner die ` _FR5000_grammar.json`  angesehen und diese hatte die "alte" Grammatikbibliothek. Nachdem ich die Datei gelöscht habe und neu importiert ging es.

**Comment by jacbz** [comment]
Habe grade einen Fix gepusht, der dieses Problem in Zukunft beheben sollte. Danke für den Hinweis!

**Comment by remggo** [comment]
Ich habe jetzt nochmal geupdated, jetzt sehe ich, dass das Deck versucht auf `_FR5000_grammar_1721258426690.json` zuzugreifen. D.h. die Version, welche du eingebaut hast, hat funktioniert. Aber ich habe das Gefühlt, dass bei einem Import die JSON und XML files fehlschlagen zu importieren bei mir (AnkiDroid & Anki Desktop auf Linux).

Weißt du ob das evtl. ein Upstream Problem sein könnte?

Andere Frage: Wie würde ich von diesem Repo zu einem frischen Anki Deck "from source" kommen? Dann könnte ich da noch ein bisschen experimentieren, warum evtl. der Import fehlschlägt. Evtl. schlägt ja auch nur der Export fehl?

**Comment by jacbz** [comment]
Hey, danke für den Hinweis. Tatsächlich scheint wohl der Export fehlerhaft gewesen sein. Ich habe das Deck nun aktualisiert, kannst du überprüfen ob der Fehler weiterhin auftritt?

Es ist momentan noch nicht möglich, das Anki-Deck von Source zu bauen (der Nutzen ist auch beschränkt, da der Lernfortschritt verloren geht). Die Änderungen hier werden nur mit meinem lokalen Deck synchronisiert. Leider bietet AnkiWeb keine API zum Hochladen von APKGs an, weswegen es sich auch nicht wirklich lohnt (wäre sonst richtig cool, hier einfach eine GitHub Pipeline zu haben, die bei jedem Commit ein Update auf AnkiWeb pusht).

**Comment by remggo** [comment]
Der Fehler mit den Grammatikfiles ist behoben, allerdings versucht Anki noch auf Kartenspezifische XML zuzugreifen. Müsste diese Zeile hier sein

https://github.com/jacbz/anki_french/blob/a797cd9c8dc59aae5d30d06530c13fc32a717772/card_templates/back.js#L580

![Screenshot_20240722_073749_AnkiDroid](https://github.com/user-attachments/assets/61a28057-df24-48b3-ab05-ee8e104ce9f8)

**Comment by jacbz** [comment]
Danke für den Hinweis. Ich habe den Teil entfernt, sodass die Fehlermeldung verschwinden müsste.

Bei den XML-Dateien handelt es sich um Wörterbuchdateien, die ich auf jeder Karte anzeigen lasse, um die Definitionen bequemer abgleichen zu können. Aus urheberrechtlichen Gründen kann ich diese leider nicht mitliefern.

**Comment by remggo** [comment]
Ah des Rätsels Lösung :) Danke dir.
