### ISSUE TITLE
Klickbare Elelmente funtkionieren nicht mehr

### ISSUE THREAD

**Issue by corgok** [jacbz/anki_french#7]
Ich habe ehute das erste Mal nach dem 22.6. ein Update geholt, und die klickbaren Elemente reagieren nicht mehr. Deshalb hab ich ein neues Profil erstellt und alle addons deaktiviert, und auch da war das der Fall. Anki auf Windows mit englischem Zahlenformat.

Ich kann die neuen Elemente sehen. Für die Übersetzung der Sätze- muss ich mit Maus über das leere Feld ziehen.
-Der Lautsprecher Knopf bei den Sätzen ist verschwunden.
-Grammatik passiert nichts
-Verben ausfalten passiert nichts
-Auf Github bearbeiten passiert nichts

Was könnte ich noch versuchen?

**Comment by jacbz** [comment]
Tritt der Fehler auch auf AnkiWeb auf? Was sagt die Konsole?

![CleanShot 2024-07-14 at 21 25 47@2x](https://github.com/user-attachments/assets/7662cdf8-2500-4574-af97-94046513913d)

**Comment by corgok** [comment]
AnkiWeb funktioniert. Klasse, dann kann ich ja da erst Mal weitermachen.Die Konsole hat mehrere Warnings.
![image](https://github.com/user-attachments/assets/a741340e-40ab-4e90-ba19-95f08b2595e2)

**Comment by jacbz** [comment]
Kannst du in der Anki-App [dieses](https://ankiweb.net/shared/info/31746032) Addon installieren und zeigen, was in der Konsole steht?

**Comment by corgok** [comment]
![image](https://github.com/user-attachments/assets/25e870dd-84d0-4329-ba28-4e412b595f35)

**Comment by jacbz** [comment]
Danke. Welche Anki-Version benutzt du?

Ich hab jetzt ein Update veröffentlicht, welches das Problem beheben sollte.

**Comment by corgok** [comment]
Danke, das update funktioniert :-) An Anki selber hatte ich gar nicht gedacht.

Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

Of topic: Ich freue mich besonders auf die Sätze auf der Startseite, weil ich darüber selber gerade nachgedacht habe. Du hast auch mehrfach-Definitionen auf der todo liste. Könnte man die nicht als Synonyme mit auf die Notizen nehmen und dann auch auf der DE->FR Startseite (evtl verdeckt) zeigen?

**Comment by jacbz** [comment]
Okay, deine Anki-Version ist über zwei Jahre alt :)

Das Problem ist, es sind oft keine wirklichen Synonyme, sondern nur ähnliche Begriffe, die nicht immer ausgetauscht werden können. Ich habe mittlerweile schon viele Notizen geschrieben, da den Unterschied zwischen zwei Begriffen erläutern. Mit dem Beispielsatz auf der Vorderseite hat man nun immerhin einen besseren Kontext.
